### ISSUE TITLE
Chunks of xyz.md are not valid / Exception raised while retrieving chunks

### ISSUE THREAD

**Issue by corani** [vrtmrz/obsidian-livesync#523]
I've updated to `0.23.23` today on both my Windows desktop and Android mobile (using couchdb backend). On my desktop I've rebuild the remote database and I'm now trying to fetch it from my mobile to rebuild the local database but am getting thousands of "Chunks of xyz.md are not valid" and "Exception raised while retrieving chunks" messages.

(1) The continuous wall of toasts make the app unusable until it eventually stops. I see some dialogs from livesync pop up behind the toasts, but they're unreadable and unusable.

(2) Am I toast, and will I have to rebuild everything from scratch? Or are there suggestions for how to recover?

**Comment by corani** [comment]
I did a "rebuild everything" on the desktop which took a while, but after that my mobile was able to pull again. Side benefit is that the database is now 10x smaller (not sure what happened there...)

**Comment by rickythewoof** [comment]
This helped me, thanks!

**Comment by vrtmrz** [comment]
Sorry for being late! This problem has been fixed at v0.24.0. And, `Rebuild everything` is the best way bring everything back to fine! (But it were possibly a bit of danger if it had not been synchronised for a while. Secondary way is `Resend chunks` on the Hatch pane. This would be safe).

Would you mind if I ask you to upgrade to the latest version and check the behaviour, please?

**Comment by caniko** [comment]
No, this doesn't work. I am still getting "Chunks are invalid"
